python new_graph_maker.py -d /homes/kgori/storage/regime2/spr -m all -s lnl -p phyml -o spr_all_lnl_phyml.pdf -x spr
python new_graph_maker.py -d /homes/kgori/storage/regime2/spr -m euc -s lnl -p phyml -o spr_euc_lnl_phyml.pdf -x spr
python new_graph_maker.py -d /homes/kgori/storage/regime2/spr -m sym -s lnl -p phyml -o spr_sym_lnl_phyml.pdf -x spr
python new_graph_maker.py -d /homes/kgori/storage/regime2/spr -m geo -s lnl -p phyml -o spr_geo_lnl_phyml.pdf -x spr
python new_graph_maker.py -d /homes/kgori/storage/regime2/spr -m all -s lnl -p bionj -o spr_all_lnl_bionj.pdf -x spr
python new_graph_maker.py -d /homes/kgori/storage/regime2/spr -m euc -s lnl -p bionj -o spr_euc_lnl_bionj.pdf -x spr
python new_graph_maker.py -d /homes/kgori/storage/regime2/spr -m sym -s lnl -p bionj -o spr_sym_lnl_bionj.pdf -x spr
python new_graph_maker.py -d /homes/kgori/storage/regime2/spr -m geo -s lnl -p bionj -o spr_geo_lnl_bionj.pdf -x spr
python new_graph_maker.py -d /homes/kgori/storage/regime2/spr -m all -s vi -p phyml -o spr_all_vi_phyml.pdf -x spr
python new_graph_maker.py -d /homes/kgori/storage/regime2/spr -m euc -s vi -p phyml -o spr_euc_vi_phyml.pdf -x spr
python new_graph_maker.py -d /homes/kgori/storage/regime2/spr -m sym -s vi -p phyml -o spr_sym_vi_phyml.pdf -x spr
python new_graph_maker.py -d /homes/kgori/storage/regime2/spr -m geo -s vi -p phyml -o spr_geo_vi_phyml.pdf -x spr
python new_graph_maker.py -d /homes/kgori/storage/regime2/spr -m all -s vi -p bionj -o spr_all_vi_bionj.pdf -x spr
python new_graph_maker.py -d /homes/kgori/storage/regime2/spr -m euc -s vi -p bionj -o spr_euc_vi_bionj.pdf -x spr
python new_graph_maker.py -d /homes/kgori/storage/regime2/spr -m sym -s vi -p bionj -o spr_sym_vi_bionj.pdf -x spr
python new_graph_maker.py -d /homes/kgori/storage/regime2/spr -m geo -s vi -p bionj -o spr_geo_vi_bionj.pdf -x spr

python new_graph_maker.py -d /homes/kgori/storage/regime2/nni -m all -s lnl -p phyml -o nni_all_lnl_phyml.pdf -x nni
python new_graph_maker.py -d /homes/kgori/storage/regime2/nni -m euc -s lnl -p phyml -o nni_euc_lnl_phyml.pdf -x nni
python new_graph_maker.py -d /homes/kgori/storage/regime2/nni -m sym -s lnl -p phyml -o nni_sym_lnl_phyml.pdf -x nni
python new_graph_maker.py -d /homes/kgori/storage/regime2/nni -m geo -s lnl -p phyml -o nni_geo_lnl_phyml.pdf -x nni
python new_graph_maker.py -d /homes/kgori/storage/regime2/nni -m all -s lnl -p bionj -o nni_all_lnl_bionj.pdf -x nni
python new_graph_maker.py -d /homes/kgori/storage/regime2/nni -m euc -s lnl -p bionj -o nni_euc_lnl_bionj.pdf -x nni
python new_graph_maker.py -d /homes/kgori/storage/regime2/nni -m sym -s lnl -p bionj -o nni_sym_lnl_bionj.pdf -x nni
python new_graph_maker.py -d /homes/kgori/storage/regime2/nni -m geo -s lnl -p bionj -o nni_geo_lnl_bionj.pdf -x nni
python new_graph_maker.py -d /homes/kgori/storage/regime2/nni -m all -s vi -p phyml -o nni_all_vi_phyml.pdf -x nni
python new_graph_maker.py -d /homes/kgori/storage/regime2/nni -m euc -s vi -p phyml -o nni_euc_vi_phyml.pdf -x nni
python new_graph_maker.py -d /homes/kgori/storage/regime2/nni -m sym -s vi -p phyml -o nni_sym_vi_phyml.pdf -x nni
python new_graph_maker.py -d /homes/kgori/storage/regime2/nni -m geo -s vi -p phyml -o nni_geo_vi_phyml.pdf -x nni
python new_graph_maker.py -d /homes/kgori/storage/regime2/nni -m all -s vi -p bionj -o nni_all_vi_bionj.pdf -x nni
python new_graph_maker.py -d /homes/kgori/storage/regime2/nni -m euc -s vi -p bionj -o nni_euc_vi_bionj.pdf -x nni
python new_graph_maker.py -d /homes/kgori/storage/regime2/nni -m sym -s vi -p bionj -o nni_sym_vi_bionj.pdf -x nni
python new_graph_maker.py -d /homes/kgori/storage/regime2/nni -m geo -s vi -p bionj -o nni_geo_vi_bionj.pdf -x nni

python new_graph_maker.py -d /homes/kgori/storage/regime2/coal -m all -s lnl -p phyml -o coal_all_lnl_phyml.pdf -x coal
python new_graph_maker.py -d /homes/kgori/storage/regime2/coal -m euc -s lnl -p phyml -o coal_euc_lnl_phyml.pdf -x coal
python new_graph_maker.py -d /homes/kgori/storage/regime2/coal -m sym -s lnl -p phyml -o coal_sym_lnl_phyml.pdf -x coal
python new_graph_maker.py -d /homes/kgori/storage/regime2/coal -m geo -s lnl -p phyml -o coal_geo_lnl_phyml.pdf -x coal
python new_graph_maker.py -d /homes/kgori/storage/regime2/coal -m all -s lnl -p bionj -o coal_all_lnl_bionj.pdf -x coal
python new_graph_maker.py -d /homes/kgori/storage/regime2/coal -m euc -s lnl -p bionj -o coal_euc_lnl_bionj.pdf -x coal
python new_graph_maker.py -d /homes/kgori/storage/regime2/coal -m sym -s lnl -p bionj -o coal_sym_lnl_bionj.pdf -x coal
python new_graph_maker.py -d /homes/kgori/storage/regime2/coal -m geo -s lnl -p bionj -o coal_geo_lnl_bionj.pdf -x coal
python new_graph_maker.py -d /homes/kgori/storage/regime2/coal -m all -s vi -p phyml -o coal_all_vi_phyml.pdf -x coal
python new_graph_maker.py -d /homes/kgori/storage/regime2/coal -m euc -s vi -p phyml -o coal_euc_vi_phyml.pdf -x coal
python new_graph_maker.py -d /homes/kgori/storage/regime2/coal -m sym -s vi -p phyml -o coal_sym_vi_phyml.pdf -x coal
python new_graph_maker.py -d /homes/kgori/storage/regime2/coal -m geo -s vi -p phyml -o coal_geo_vi_phyml.pdf -x coal
python new_graph_maker.py -d /homes/kgori/storage/regime2/coal -m all -s vi -p bionj -o coal_all_vi_bionj.pdf -x coal
python new_graph_maker.py -d /homes/kgori/storage/regime2/coal -m euc -s vi -p bionj -o coal_euc_vi_bionj.pdf -x coal
python new_graph_maker.py -d /homes/kgori/storage/regime2/coal -m sym -s vi -p bionj -o coal_sym_vi_bionj.pdf -x coal
python new_graph_maker.py -d /homes/kgori/storage/regime2/coal -m geo -s vi -p bionj -o coal_geo_vi_bionj.pdf -x coal